### ISSUE TITLE
Enhance UI/UX with Green Theme and Interactive Player Management

### ISSUE THREAD

**Issue by Zoros-GPS** [Zoros-GPS/tes1#1]
## Current Issues
1. Color theme needs to be changed to an inspiring green theme
2. File upload section is too large and not elegant
3. Player management interface is not intuitive (using text input and toggle)
4. Team number displays are not easily visible
5. Player names are hard to distinguish
6. Team display needs role-wise organization

### Overall Theme Update
- Change the gradient background from purple to green theme:
  ```css
  body {
      background: linear-gradient(135deg, #2ecc71 0%, #27ae60 100%);
  }
  ```
- Update all accent colors and buttons to match the green theme
- Use a softer, more professional green palette (#2ecc71, #27ae60, #229954)

### File Upload Section
- Reduce the size of the upload section by 40%
- Make it more compact and elegant:
  ```css
  .upload-section {
      padding: 20px;
      max-width: 600px;
      margin: 0 auto 20px;
  }
  ```
- Use a subtle icon-based design for the file input

### Player Management Interface
- Remove the text input and toggle button system
- Implement clickable player cards:
  ```css
  .player-item {
      cursor: pointer;
      transition: all 0.3s ease;
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 12px 20px;
      margin: 8px 0;
      border-radius: 10px;
      background: white;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
  }
  
  .player-item:hover {
      transform: translateY(-2px);
      box-shadow: 0 4px 8px rgba(0,0,0,0.15);
  }
  ```
- Add visual feedback for active/inactive states
- Include a clear visual indicator for selected/deselected players

### Team Number Display
- Make team numbers more prominent:
  ```css
  .team-count {
      font-size: 1.25em;
      font-weight: 700;
      background: #2ecc71;
      color: white;
      padding: 8px 16px;
      border-radius: 20px;
      min-width: 45px;
      text-align: center;
  }
  ```

### Player Name Readability
- Improve typography and spacing:
  ```css
  .player-name {
      font-size: 1.1em;
      font-weight: 500;
      color: #2c3e50;
      flex: 1;
      margin-right: 20px;
      letter-spacing: 0.2px;
  }
  
  .player-item.removed .player-name {
      color: #95a5a6;
      text-decoration: line-through;
  }
  ```

### Role-based Team Display
- Modify the showTeams() function
